apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: go-web-server
  name: go-web-server
  namespace: golang-s2i-app
spec:
  ports:
  - name: 9090-tcp
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: go-web-server
    deploymentconfig: go-web-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
