apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: go-web-server
    name: go-web-server
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: go-web-server:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: http://services.lab.example.com/gopl.io
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: golang-builder:v1.0
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 4N_fq_yM-eVWSDuBbCrG
      type: GitHub
    - generic:
        secret: IilLgj1WSTxTOsnXPkdE
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: go-web-server
    name: go-web-server
  spec:
    replicas: 1
    selector:
      app: go-web-server
      deploymentconfig: go-web-server
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: go-web-server
          deploymentconfig: go-web-server
      spec:
        containers:
        - image: go-web-server:latest
          name: go-web-server
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - go-web-server
        from:
          kind: ImageStreamTag
          name: go-web-server:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
