services:
  db-admin:
    image: "quay.io/alberthua/crunchy-pgadmin4:ubi8-4.30-18"
    # mirror image from registry.connect.redhat.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-18
    container_name: "compose_environments_pgadmin"
    environment:
      PGADMIN_SETUP_EMAIL: user@redhat.com
      PGADMIN_SETUP_PASSWORD: redhat
    ports:
      - "5050:5050"
  db:
    image: "quay.io/alberthua/postgresql-13:1"
    # mirror image from registry.redhat.io/rhel9/postgresql-13:1
    container_name: "compose_environments_postgresql"
    environment:
      POSTGRESQL_USER: backend
      POSTGRESQL_DATABASE: rpi-store
      POSTGRESQL_PASSWORD: redhat
    ports:
      - "5432:5432"
    volumes:
      - ./database_scripts:/opt/app-root/src/postgresql-start:Z
      - rpi:/var/lib/pgsql/data
volumes:
  rpi: {}
